[server]
name = 'gogobar'
apidoc = './apidoc'
apiurl = 'http://localhost:8000'
ignore_urls = ["/", "/home", "/user/login", "/user/registe"]
jwt_timeout = 7   # token 过期天数
jwt_prefix = "Bearer"   # token 前缀

[test]
loglevel = 'info'
user = 'admin'
pass = 'qwert@12345'
role = 'admin'
[test.database]
driver = "sqlite3"
connect = "test.db"

[prod]
loglevel = 'info'
[prod.database]
driver = "mysql"
connect = "iris:iris@tcp(localhost:3306)/iris?charset=utf8&parseTime=True"